const endpoints = {
  urlBase: 'http://192.168.0.37:8080/rest/v1/user/',
  urlAnon: 'http://192.168.0.37:8080/rest/v1/anon/',
  // urlBase: 'http://192.168.1.7:8080/rest/v1/user/',
  // urlAnon: 'http://192.168.1.7:8080/rest/v1/anon/',
  login: 'login',
  logout: 'logout',
  keepAlive: 'keepAlive',
  getUserProfile: 'getUserProfile',
  createBuilding: 'createBuilding',
  getBuildings: 'getBuildings',
  updateBuilding: 'updateBuilding',
  deleteBuilding: 'deleteBuilding',
  createApartment: 'createApartment',
  getApartments: 'getApartments',
  updateApartment: 'updateApartment',
  deleteApartment: 'deleteApartment',
  createTask: 'createTask',
  getTasks: 'getTasks',
  getBuildingTasks: 'getTasksByBuildingId',
  updateTask: 'updateTask',
  changeTaskStatus: 'changeTaskStatus',
  deleteTask: 'deleteTask',
  createMessage: 'createMessage',
  getBuildingMessages: 'getBuildingMessages',
  getApartmentMessages: 'getApartmentMessages',
  updateMessage: 'updateMessage',
  deleteMessage: 'deleteMessage',
  markMessageAsRead: 'markMessageAsRead',
  createMonitoring: 'createMonitoring',
  getBuildingMonitorings: 'getBuildingMonitorings',
  getBuildingMonitoringsByCategory: 'getBuildingMonitoringsByCategory',
  updateMonitoring: 'updateMonitoring',
  deleteMonitoring: 'deleteMonitoring',
  createTaskCategory: 'createTaskCategory',
  getTaskCategories: 'getTaskCategories',
  getBuildingTaskCategories: 'getBuildingTaskCategories',
  updateTaskCategory: 'updateTaskCategory',
  deleteTaskCategory: 'deleteTaskCategory',
  createMonitoringCategory: 'createMonitoringCategory',
  getMonitoringCategories: 'getMonitoringCategories',
  getBuildingMonitoringCategories: 'getBuildingMonitoringCategories',
  updateMonitoringCategory: 'updateMonitoringCategory',
  deleteMonitoringCategory: 'deleteMonitoringCategory',
  changePassword: 'update_password' // !!!!not implemented on server side jet!!!!!
};

export default endpoints;
