export const GET_BUILDING_APARTMENTS = 'GET_BUILDING_APARTMENTS';
export const GET_BUILDING_APARTMENTS_SUCCESS =
  'GET_BUILDING_APARTMENTS_SUCCESS';
export const GET_BUILDING_APARTMENTS_FAILURE =
  'GET_BUILDING_APARTMENTS_FAILURE';

export const CREATE_APARTMENT = 'CREATE_APARTMENT';
export const CREATE_APARTMENT_SUCCESS = 'CREATE_APARTMENT_SUCCESS';
export const CREATE_APARTMENT_FAILURE = 'CREATE_APARTMENT_FAILURE';

export const UPDATE_APARTMENT = 'UPDATE_APARTMENT';
export const UPDATE_APARTMENT_SUCCESS = 'UPDATE_APARTMENT_SUCCESS';
export const UPDATE_APARTMENT_FAILURE = 'UPDATE_APARTMENT_FAILURE';

export const DELETE_APARTMENT = 'DELETE_APARTMENT';
export const DELETE_APARTMENT_SUCCESS = 'DELETE_APARTMENT_SUCCESS';
export const DELETE_APARTMENT_FAILURE = 'DELETE_APARTMENT_FAILURE';

export const CLEAN_UP_ERRORS = 'CLEAN_UP_ERRORS';
