const GET_BUILDING_APARTMENTS = 'GET_BUILDING_APARTMENTS';
const GET_BUILDING_APARTMENTS_SUCCESS = 'GET_BUILDING_APARTMENTS_SUCCESS';
const GET_BUILDING_APARTMENTS_FAILED = 'GET_BUILDING_APARTMENTS_FAILED';

const CREATE_APARTMENT = 'CREATE_APARTMENT';
const CREATE_APARTMENT_SUCCESS = 'CREATE_APARTMENT_SUCCESS';
const CREATE_APARTMENT_FAILED = 'CREATE_APARTMENT_FAILED';

const UPDATE_APARTMENT = 'UPDATE_APARTMENT';
const UPDATE_APARTMENT_SUCCESS = 'UPDATE_APARTMENT_SUCCESS';
const UPDATE_APARTMENT_FAILED = 'UPDATE_APARTMENT_FAILED';

const DELETE_APARTMENT = 'DELETE_APARTMENT';
const DELETE_APARTMENT_SUCCESS = 'DELETE_APARTMENT_SUCCESS';
const DELETE_APARTMENT_FAILED = 'DELETE_APARTMENT_FAILED';

export {
  GET_BUILDING_APARTMENTS,
  GET_BUILDING_APARTMENTS_SUCCESS,
  GET_BUILDING_APARTMENTS_FAILED,
  CREATE_APARTMENT,
  CREATE_APARTMENT_SUCCESS,
  CREATE_APARTMENT_FAILED,
  UPDATE_APARTMENT,
  UPDATE_APARTMENT_SUCCESS,
  UPDATE_APARTMENT_FAILED,
  DELETE_APARTMENT,
  DELETE_APARTMENT_SUCCESS,
  DELETE_APARTMENT_FAILED
};
