const GET_BUILDINGS = 'GET_BUILDINGS';
const GET_BUILDINGS_SUCCESS = 'GET_BUILDINGS_SUCCESS';
const GET_BUILDINGS_FAILED = 'GET_BUILDINGS_FAILED';

const CREATE_BUILDING = 'CREATE_BUILDING';
const CREATE_BUILDING_SUCCESS = 'CREATE_BUILDING_SUCCESS';
const CREATE_BUILDING_FAILED = 'CREATE_BUILDING_FAILED';

const UPDATE_BUILDING = 'UPDATE_BUILDING';
const UPDATE_BUILDING_SUCCESS = 'UPDATE_BUILDING_SUCCESS';
const UPDATE_BUILDING_FAILED = 'UPDATE_BUILDING_FAILED';

const DELETE_BUILDING = 'DELETE_BUILDING';
const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS';
const DELETE_BUILDING_FAILED = 'DELETE_BUILDING_FAILED';

export {
  GET_BUILDINGS,
  GET_BUILDINGS_SUCCESS,
  GET_BUILDINGS_FAILED,
  CREATE_BUILDING,
  CREATE_BUILDING_SUCCESS,
  CREATE_BUILDING_FAILED,
  UPDATE_BUILDING,
  UPDATE_BUILDING_SUCCESS,
  UPDATE_BUILDING_FAILED,
  DELETE_BUILDING,
  DELETE_BUILDING_SUCCESS,
  DELETE_BUILDING_FAILED
};
