const GET_BUILDING_MESSAGES = 'GET_BUILDING_MESSAGES';
const GET_BUILDING_MESSAGES_SUCCESS = 'GET_BUILDING_MESSAGES_SUCCESS';
const GET_BUILDING_MESSAGES_FAILED = 'GET_BUILDING_MESSAGES_FAILED';

const GET_APARTMENT_MESSAGES = 'GET_APARTMENT_MESSAGES';
const GET_APARTMENT_MESSAGES_SUCCESS = 'GET_APARTMENT_MESSAGES_SUCCESS';
const GET_APARTMENT_MESSAGES_FAILED = 'GET_APARTMENT_MESSAGES_FAILED';

const CREATE_MESSAGE = 'CREATE_MESSAGE';
const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
const CREATE_MESSAGE_FAILED = 'CREATE_MESSAGE_FAILED';

const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
const UPDATE_MESSAGE_FAILED = 'UPDATE_MESSAGE_FAILED';

const DELETE_MESSAGE = 'DELETE_MESSAGE';
const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
const DELETE_MESSAGE_FAILED = 'DELETE_MESSAGE_FAILED';

export {
  GET_BUILDING_MESSAGES,
  GET_BUILDING_MESSAGES_SUCCESS,
  GET_BUILDING_MESSAGES_FAILED,
  GET_APARTMENT_MESSAGES,
  GET_APARTMENT_MESSAGES_SUCCESS,
  GET_APARTMENT_MESSAGES_FAILED,
  CREATE_MESSAGE,
  CREATE_MESSAGE_SUCCESS,
  CREATE_MESSAGE_FAILED,
  UPDATE_MESSAGE,
  UPDATE_MESSAGE_SUCCESS,
  UPDATE_MESSAGE_FAILED,
  DELETE_MESSAGE,
  DELETE_MESSAGE_SUCCESS,
  DELETE_MESSAGE_FAILED
};
