export const GET_BUILDING_MESSAGES = 'GET_BUILDING_MESSAGES';
export const GET_BUILDING_MESSAGES_SUCCESS = 'GET_BUILDING_MESSAGES_SUCCESS';
export const GET_BUILDING_MESSAGES_FAILURE = 'GET_BUILDING_MESSAGES_FAILURE';

export const GET_APARTMENT_MESSAGES = 'GET_APARTMENT_MESSAGES';
export const GET_APARTMENT_MESSAGES_SUCCESS = 'GET_APARTMENT_MESSAGES_SUCCESS';
export const GET_APARTMENT_MESSAGES_FAILURE = 'GET_APARTMENT_MESSAGES_FAILURE';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE';

export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_FAILURE = 'UPDATE_MESSAGE_FAILURE';

export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAILURE = 'DELETE_MESSAGE_FAILURE';
