const GET_BUILDING_MONITORING_CATEGORIES = 'GET_BUILDING_MONITORING_CATEGORIES';
const GET_BUILDING_MONITORING_CATEGORIES_SUCCESS =
  'GET_BUILDING_MONITORING_CATEGORIES_SUCCESS';
const GET_BUILDING_MONITORING_CATEGORIES_FAILED =
  'GET_BUILDING_MONITORING_CATEGORIES_FAILED';

const CREATE_MONITORING_CATEGORY = 'CREATE_MONITORING_CATEGORY';
const CREATE_MONITORING_CATEGORY_SUCCESS = 'CREATE_MONITORING_CATEGORY_SUCCESS';
const CREATE_MONITORING_CATEGORY_FAILED = 'CREATE_MONITORING_CATEGORY_FAILED';

const UPDATE_MONITORING_CATEGORY = 'UPDATE_MONITORING_CATEGORY';
const UPDATE_MONITORING_CATEGORY_SUCCESS = 'UPDATE_MONITORING_CATEGORY_SUCCESS';
const UPDATE_MONITORING_CATEGORY_FAILED = 'UPDATE_MONITORING_CATEGORY_FAILED';

const DELETE_MONITORING_CATEGORY = 'DELETE_MONITORING_CATEGORY';
const DELETE_MONITORING_CATEGORY_SUCCESS = 'DELETE_MONITORING_CATEGORY_SUCCESS';
const DELETE_MONITORING_CATEGORY_FAILED = 'DELETE_MONITORING_CATEGORY_FAILED';

export {
  GET_BUILDING_MONITORING_CATEGORIES,
  GET_BUILDING_MONITORING_CATEGORIES_SUCCESS,
  GET_BUILDING_MONITORING_CATEGORIES_FAILED,
  CREATE_MONITORING_CATEGORY,
  CREATE_MONITORING_CATEGORY_SUCCESS,
  CREATE_MONITORING_CATEGORY_FAILED,
  UPDATE_MONITORING_CATEGORY,
  UPDATE_MONITORING_CATEGORY_SUCCESS,
  UPDATE_MONITORING_CATEGORY_FAILED,
  DELETE_MONITORING_CATEGORY,
  DELETE_MONITORING_CATEGORY_SUCCESS,
  DELETE_MONITORING_CATEGORY_FAILED
};
