export const GET_BUILDING_MONITORING_CATEGORIES =
  'GET_BUILDING_MONITORING_CATEGORIES';
export const GET_BUILDING_MONITORING_CATEGORIES_SUCCESS =
  'GET_BUILDING_MONITORING_CATEGORIES_SUCCESS';
export const GET_BUILDING_MONITORING_CATEGORIES_FAILURE =
  'GET_BUILDING_MONITORING_CATEGORIES_FAILURE';

export const CREATE_MONITORING_CATEGORY = 'CREATE_MONITORING_CATEGORY';
export const CREATE_MONITORING_CATEGORY_SUCCESS =
  'CREATE_MONITORING_CATEGORY_SUCCESS';
export const CREATE_MONITORING_CATEGORY_FAILURE =
  'CREATE_MONITORING_CATEGORY_FAILURE';

export const UPDATE_MONITORING_CATEGORY = 'UPDATE_MONITORING_CATEGORY';
export const UPDATE_MONITORING_CATEGORY_SUCCESS =
  'UPDATE_MONITORING_CATEGORY_SUCCESS';
export const UPDATE_MONITORING_CATEGORY_FAILURE =
  'UPDATE_MONITORING_CATEGORY_FAILURE';

export const DELETE_MONITORING_CATEGORY = 'DELETE_MONITORING_CATEGORY';
export const DELETE_MONITORING_CATEGORY_SUCCESS =
  'DELETE_MONITORING_CATEGORY_SUCCESS';
export const DELETE_MONITORING_CATEGORY_FAILURE =
  'DELETE_MONITORING_CATEGORY_FAILURE';
