const GET_BUILDING_MONITORINGS = 'GET_BUILDING_MONITORINGS';
const GET_BUILDING_MONITORINGS_SUCCESS = 'GET_BUILDING_MONITORINGS_SUCCESS';
const GET_BUILDING_MONITORINGS_FAILED = 'GET_BUILDING_MONITORINGS_FAILED';

const GET_BUILDING_AND_CATEGORY_MONITORINGS =
  'GET_BUILDING_AND_CATEGORY_MONITORINGS';
const GET_BUILDING_AND_CATEGORY_MONITORINGS_SUCCESS =
  'GET_BUILDING_AND_CATEGORY_MONITORINGS_SUCCESS';
const GET_BUILDING_AND_CATEGORY_MONITORINGS_FAILED =
  'GET_BUILDING_AND_CATEGORY_MONITORINGS_FAILED';

const CREATE_MONITORING = 'CREATE_MONITORING';
const CREATE_MONITORING_SUCCESS = 'CREATE_MONITORING_SUCCESS';
const CREATE_MONITORING_FAILED = 'CREATE_MONITORING_FAILED';

const UPDATE_MONITORING = 'UPDATE_MONITORING';
const UPDATE_MONITORING_SUCCESS = 'UPDATE_MONITORING_SUCCESS';
const UPDATE_MONITORING_FAILED = 'UPDATE_MONITORING_FAILED';

const DELETE_MONITORING = 'DELETE_MONITORING';
const DELETE_MONITORING_SUCCESS = 'DELETE_MONITORING_SUCCESS';
const DELETE_MONITORING_FAILED = 'DELETE_MONITORING_FAILED';

export {
  GET_BUILDING_MONITORINGS,
  GET_BUILDING_MONITORINGS_SUCCESS,
  GET_BUILDING_MONITORINGS_FAILED,
  GET_BUILDING_AND_CATEGORY_MONITORINGS,
  GET_BUILDING_AND_CATEGORY_MONITORINGS_SUCCESS,
  GET_BUILDING_AND_CATEGORY_MONITORINGS_FAILED,
  CREATE_MONITORING,
  CREATE_MONITORING_SUCCESS,
  CREATE_MONITORING_FAILED,
  UPDATE_MONITORING,
  UPDATE_MONITORING_SUCCESS,
  UPDATE_MONITORING_FAILED,
  DELETE_MONITORING,
  DELETE_MONITORING_SUCCESS,
  DELETE_MONITORING_FAILED
};
