export const GET_BUILDING_MONITORINGS = 'GET_BUILDING_MONITORINGS';
export const GET_BUILDING_MONITORINGS_SUCCESS =
  'GET_BUILDING_MONITORINGS_SUCCESS';
export const GET_BUILDING_MONITORINGS_FAILURE =
  'GET_BUILDING_MONITORINGS_FAILURE';

export const GET_BUILDING_AND_CATEGORY_MONITORINGS =
  'GET_BUILDING_AND_CATEGORY_MONITORINGS';
export const GET_BUILDING_AND_CATEGORY_MONITORINGS_SUCCESS =
  'GET_BUILDING_AND_CATEGORY_MONITORINGS_SUCCESS';
export const GET_BUILDING_AND_CATEGORY_MONITORINGS_FAILURE =
  'GET_BUILDING_AND_CATEGORY_MONITORINGS_FAILURE';

export const CREATE_MONITORING = 'CREATE_MONITORING';
export const CREATE_MONITORING_SUCCESS = 'CREATE_MONITORING_SUCCESS';
export const CREATE_MONITORING_FAILURE = 'CREATE_MONITORING_FAILURE';

export const UPDATE_MONITORING = 'UPDATE_MONITORING';
export const UPDATE_MONITORING_SUCCESS = 'UPDATE_MONITORING_SUCCESS';
export const UPDATE_MONITORING_FAILURE = 'UPDATE_MONITORING_FAILURE';

export const DELETE_MONITORING = 'DELETE_MONITORING';
export const DELETE_MONITORING_SUCCESS = 'DELETE_MONITORING_SUCCESS';
export const DELETE_MONITORING_FAILURE = 'DELETE_MONITORING_FAILURE';
