export const GET_BUILDING_TASKS = 'GET_BUILDING_TASKS';
export const GET_BUILDING_TASKS_SUCCESS = 'GET_BUILDING_TASKS_SUCCESS';
export const GET_BUILDING_TASKS_FAILURE = 'GET_BUILDING_TASKS_FAILURE';

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const CHANGE_TASK_STATUS_SUCCESS = 'CHANGE_TASK_STATUS_SUCCESS';
export const CHANGE_TASK_STATUS_FAILURE = 'CHANGE_TASK_STATUS_FAILURE';

export const CLEAN_UP_EDITOR_ERRORS = 'CLEAN_UP_EDITOR_ERRORS';
