const GET_BUILDING_TASK_CATEGORIES = 'GET_BUILDING_TASK_CATEGORIES';
const GET_BUILDING_TASK_CATEGORIES_SUCCESS =
  'GET_BUILDING_TASK_CATEGORIES_SUCCESS';
const GET_BUILDING_TASK_CATEGORIES_FAILED =
  'GET_BUILDING_TASK_CATEGORIES_FAILED';

const CREATE_TASK_CATEGORY = 'CREATE_TASK_CATEGORY';
const CREATE_TASK_CATEGORY_SUCCESS = 'CREATE_TASK_CATEGORY_SUCCESS';
const CREATE_TASK_CATEGORY_FAILED = 'CREATE_TASK_CATEGORY_FAILED';

const UPDATE_TASK_CATEGORY = 'UPDATE_TASK_CATEGORY';
const UPDATE_TASK_CATEGORY_SUCCESS = 'UPDATE_TASK_CATEGORY_SUCCESS';
const UPDATE_TASK_CATEGORY_FAILED = 'UPDATE_TASK_CATEGORY_FAILED';

const DELETE_TASK_CATEGORY = 'DELETE_TASK_CATEGORY';
const DELETE_TASK_CATEGORY_SUCCESS = 'DELETE_TASK_CATEGORY_SUCCESS';
const DELETE_TASK_CATEGORY_FAILED = 'DELETE_TASK_CATEGORY_FAILED';

export {
  GET_BUILDING_TASK_CATEGORIES,
  GET_BUILDING_TASK_CATEGORIES_SUCCESS,
  GET_BUILDING_TASK_CATEGORIES_FAILED,
  CREATE_TASK_CATEGORY,
  CREATE_TASK_CATEGORY_SUCCESS,
  CREATE_TASK_CATEGORY_FAILED,
  UPDATE_TASK_CATEGORY,
  UPDATE_TASK_CATEGORY_SUCCESS,
  UPDATE_TASK_CATEGORY_FAILED,
  DELETE_TASK_CATEGORY,
  DELETE_TASK_CATEGORY_SUCCESS,
  DELETE_TASK_CATEGORY_FAILED
};
