const GET_BUILDING_TASKS = 'GET_BUILDING_TASKS';
const GET_BUILDING_TASKS_SUCCESS = 'GET_BUILDING_TASKS_SUCCESS';
const GET_BUILDING_TASKS_FAILED = 'GET_BUILDING_TASKS_FAILED';

const CREATE_TASK = 'CREATE_TASK';
const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
const CREATE_TASK_FAILED = 'CREATE_TASK_FAILED';

const UPDATE_TASK = 'UPDATE_TASK';
const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';

const DELETE_TASK = 'DELETE_TASK';
const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';

export {
  GET_BUILDING_TASKS,
  GET_BUILDING_TASKS_SUCCESS,
  GET_BUILDING_TASKS_FAILED,
  CREATE_TASK,
  CREATE_TASK_SUCCESS,
  CREATE_TASK_FAILED,
  UPDATE_TASK,
  UPDATE_TASK_SUCCESS,
  UPDATE_TASK_FAILED,
  DELETE_TASK,
  DELETE_TASK_SUCCESS,
  DELETE_TASK_FAILED
};
