export const GET_TASK_CATEGORIES = 'GET_TASK_CATEGORIES';
export const GET_TASK_CATEGORIES_SUCCESS = 'GET_TASK_CATEGORIES_SUCCESS';
export const GET_TASK_CATEGORIES_FAILURE = 'GET_TASK_CATEGORIES_FAILURE';
export const GET_BUILDING_TASK_CATEGORIES = 'GET_BUILDING_TASK_CATEGORIES';
export const GET_BUILDING_TASK_CATEGORIES_SUCCESS =
  'GET_BUILDING_TASK_CATEGORIES_SUCCESS';
export const GET_BUILDING_TASK_CATEGORIES_FAILURE =
  'GET_BUILDING_TASK_CATEGORIES_FAILURE';
export const CREATE_TASK_CATEGORY = 'CREATE_TASK_CATEGORY';
export const CREATE_TASK_CATEGORY_SUCCESS = 'CREATE_TASK_CATEGORY_SUCCESS';
export const CREATE_TASK_CATEGORY_FAILURE = 'CREATE_TASK_CATEGORY_FAILURE';

export const UPDATE_TASK_CATEGORY = 'UPDATE_TASK_CATEGORY';
export const UPDATE_TASK_CATEGORY_SUCCESS = 'UPDATE_TASK_CATEGORY_SUCCESS';
export const UPDATE_TASK_CATEGORY_FAILURE = 'UPDATE_TASK_CATEGORY_FAILURE';

export const DELETE_TASK_CATEGORY = 'DELETE_TASK_CATEGORY';
export const DELETE_TASK_CATEGORY_SUCCESS = 'DELETE_TASK_CATEGORY_SUCCESS';
export const DELETE_TASK_CATEGORY_FAILURE = 'DELETE_TASK_CATEGORY_FAILURE';
export const CLEAN_UP_TASK_CATEGORY_ERRORS = 'CLEAN_UP_TASK_CATEGORY_ERRORS';
